name: Fill brrr.cz daily history

on:
  schedule:
    - cron: "0 2 * * *"   # každý den v 02:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Fill yesterday history from brrr.cz
        run: python3 scripts/fill_brrr_day.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add docs/data/history.csv
          git commit -m "Fill yesterday history from brrr.cz" || echo "No changes to commit"
          git push
