name: Pull Tmep.cz data

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Ensure data dir and header
        run: |
          mkdir -p data
          if [ ! -f data/history.csv ]; then
            echo "timestamp_iso,temp_c,humidity_pct" > data/history.csv
          fi

      - name: Fetch JSON from tmep.cz
        run: |
          URL="https://tmep.cz/vystup-json.php?id=${{ secrets.TMEP_ID }}&export_key=${{ secrets.TMEP_KEY }}"
          echo "Fetching: $URL"
          RESP=$(curl -s "$URL")
          echo "Response: $RESP"

          TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          TEMP=$(echo "$RESP" | jq -r '.teplota // .temperature // .temp // empty')
          HUM=$(echo "$RESP"  | jq -r '.vlhkost // .humidity // .hum // empty')

          # Převod čárka -> tečka
          TEMP=$(echo "$TEMP" | sed 's/,/./')
          HUM=$(echo "$HUM"   | sed 's/,/./')

          echo "$TS,$TEMP,$HUM" >> data/history.csv

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/history.csv
          git diff --cached --quiet && echo "No new data, skip commit." && exit 0
          git commit -m "data: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          git push
