name: Rotate history file

on:
  schedule:
    - cron: "5 0 1 * *"   # každý 1. den v měsíci v 00:05 UTC
  workflow_dispatch:      # možnost ručního spuštění

permissions:
  contents: write

jobs:
  rotate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        # Potřebujeme pytz pro fetch_data (předpokládáme, že se spouští jinde) 
        # a python-dateutil pro rotaci (odečet měsíce)
        run: pip install pytz python-dateutil

      - name: Run rotation script
        # Přejmenuje history.csv na history_RRRR_MM.csv (za minulý měsíc) a založí nový prázdný history.csv
        run: python3 scripts/rotate_history.py

      - name: Update index.json
        # Aktualizuje index.json o cestu k novému archivnímu souboru
        run: python3 scripts/update_index.py

      - name: Commit & push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          # Commit všech relevantních souborů: nový history.csv, archivní soubor, aktualizovaný index.json
          git add docs/data/history.csv docs/data/history_*.csv index.json
          git commit -m "Rotate history files and update index" || echo "No changes to commit"
          git push origin HEAD:main
