name: Rotate history

on:
  schedule:
    - cron: "5 0 1 * *"   # 1. den v měsíci v 00:05 UTC
  workflow_dispatch:       # možnost spustit ručně

permissions:
  contents: write   # <-- důležité pro commit a push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run rotation script
        run: python3 docs/data/rotate_history.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add docs/data/history*.csv docs/data/index.json
          git commit -m "Monthly rotate history.csv" || echo "No changes to commit"
          git push
