name: Update brrr.cz data

on:
  schedule:
    - cron: "*/10 * * * *"   # každých 10 minut
  workflow_dispatch:          # možnost ručního spuštění

permissions:
  contents: write   # <-- důležité pro commit a push

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Append last values from brrr.cz
        run: python3 scripts/append_brrr.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git pull --rebase origin main
          git add docs/data/history.csv
          git commit -m "Append brrr.cz data" || echo "No changes to commit"
          git push
